---
title: iune's lab
timezone: Europe/Paris
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Iune Trecet -en laborategia | Iune's lab
author:
  name: Iune Trecet Obeso
  email: contact@iune.info
  github: iunetrecet
  flickr: https://flickr.com/photos/iunetrecet/
exclude:
- ".rvmrc"
- ".rbenv-version"
- Rakefile
- vendor
excerpt_separator: "\n"
markdown: kramdown
